/**
 * Minimal Next.js (App Router) starter template.
 * Keys are workspace-relative paths (always rooted at /).
 */
export const NEXTJS_FILES: Record<string, string> = {
  "/package.json": JSON.stringify(
    {
      name: "my-nextjs-app",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "14.2.5",
        react: "^18",
        "react-dom": "^18",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^18",
        "@types/react-dom": "^18",
        typescript: "^5",
      },
    },
    null,
    2,
  ),

  "/tsconfig.json": JSON.stringify(
    {
      compilerOptions: {
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  ),

  "/next.config.ts": `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`,

  "/app/layout.tsx": `export const metadata = {
  title: "My Next.js App",
  description: "Generated by bolt.everything",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,

  "/app/page.tsx": `export default function Home() {
  return (
    <main>
      <h1>Hello from Next.js</h1>
      <p>Edit <code>app/page.tsx</code> to get started.</p>
    </main>
  );
}
`,

  "/.gitignore": `node_modules
.next
out
.env
.env.local
`,
};
